name: Node.js Package

on:
  push:
    branches:
      - main  # Change this to your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          FICHARIO_EMAIL_MASTER: ${{ secrets.FICHARIO_EMAIL_MASTER }}
          FICHARIO_PASSWORD_MASTER: ${{ secrets.FICHARIO_PASSWORD_MASTER }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}